("United States", "🇺🇸"), ("China", "🇨🇳"), ("Brazil", "🇧🇷"), ("Russia", "🇷🇺"),
("United Kingdom", "🇬🇧"), ("Germany", "🇩🇪"), ("France", "🇫🇷"), ("Italy", "🇮🇹"),
("Canada", "🇨🇦"), ("Spain", "🇪🇸"), ("Japan", "🇯🇵"), ("South Korea", "🇰🇷"),
("Australia", "🇦🇺"), ("Netherlands", "🇳🇱"), ("Sweden", "🇸🇪"), ("Switzerland", "🇨🇭"),
("Norway", "🇳🇴"), ("Denmark", "🇩🇰"), ("Belgium", "🇧🇪"), ("Finland", "🇫🇮"),
("Ireland", "🇮🇪"), ("Singapore", "🇸🇬"), ("Malaysia", "🇲🇾"), ("Thailand", "🇹🇭"),
("New Zealand", "🇳🇿"), ("Saudi Arabia", "🇸🇦"), ("Argentina", "🇦🇷"),
("Colombia", "🇨🇴"), ("Chile", "🇨🇱"), ("South Africa", "🇿🇦"), ("Nigeria", "🇳🇬"),
("Egypt", "🇪🇬"), ("Pakistan", "🇵🇰"), ("Bangladesh", "🇧🇩"), ("Israel", "🇮🇱"),
("Greece", "🇬🇷"), ("Portugal", "🇵🇹"), ("Czechia", "🇨🇿"), ("Poland", "🇵🇱"),
("Hungary", "🇭🇺"), ("Austria", "🇦🇹"), ("Romania", "🇷🇴"), ("Bulgaria", "🇧🇬"),
("Slovakia", "🇸🇰"), ("Croatia", "🇭🇷"), ("Serbia", "🇷🇸"), ("Albania", "🇦🇱"),
("Slovenia", "🇸🇮"), ("Estonia", "🇪🇪"), ("Latvia", "🇱🇻"), ("Lithuania", "🇱🇹"),
("Iceland", "🇮🇸"), ("Ukraine", "🇺🇦"), ("Belarus", "🇧🇾"), ("Georgia", "🇬🇪"),
("Kazakhstan", "🇰🇿"), ("Uzbekistan", "🇺🇿"), ("Kyrgyzstan", "🇰🇬"), ("Mongolia", "🇲🇳"),
("Myanmar", "🇲🇲"), ("Laos", "🇱🇦"), ("Cambodia", "🇰🇭"), ("Nepal", "🇳🇵"),
("Bhutan", "🇧🇹"), ("Sri Lanka", "🇱🇰"), ("Maldives", "🇲🇻"), ("Afghanistan", "🇦🇫"),
("Iran", "🇮🇷"), ("Iraq", "🇮🇶"), ("Syria", "🇸🇾"), ("Lebanon", "🇱🇧"),
("Jordan", "🇯🇴"), ("Palestine", "🇵🇸"), ("Oman", "🇴🇲"), ("Yemen", "🇾🇪"),
("Qatar", "🇶🇦"), ("Kuwait", "🇰🇼"), ("Bahrain", "🇧🇭"), ("UAE", "🇦🇪"),
("Morocco", "🇲🇦"), ("Algeria", "🇩🇿"), ("Tunisia", "🇹🇳"), ("Libya", "🇱🇾"),
("Sudan", "🇸🇩"), ("Ethiopia", "🇪🇹"), ("Kenya", "🇰🇪"), ("Tanzania", "🇹🇿"),
("Uganda", "🇺🇬"), ("Rwanda", "🇷🇼"), ("Zambia", "🇿🇲"), ("Zimbabwe", "🇿🇼"),
("Botswana", "🇧🇼"), ("Namibia", "🇳🇦"), ("Angola", "🇦🇴"), ("Mozambique", "🇲🇿"),